[iOS] Update limitations. (#875)
* [iOS] Remove restriction about P/Invokes in generic types.

csc doesn't allow this code anymore:

    $ cat test.cs
    class G<T>
    {
    	[System.Runtime.InteropServices.DllImport ("libc")]
    	static extern void exit ();
    }

    $ csc /t:library test.cs /nologo
    test.cs(3,3): error CS7042: The DllImport attribute cannot be applied to a method that is generic or contained in a generic type.

so there's no need for us to list this limitation, since nobody will run into
it.

* [iOS] Remove limitation about Property.SetInfo on a nullable type.

There's no such thing as `Property.SetInfo`, so at the very least the text is
wrong. It could mean `PropertyInfo.SetValue`, but that doesn't work either,
because the nullable Value property is read-only. And finally, trying to set
the `_value` field on a nullable instance works just fine.

* [iOS] Remove limitation about value types as dictionary keys.

It works fine now.

* [iOS] Update language a little bit.

There are more iOS devices than just iPhones now.